language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - openssl aes-256-cbc -K $encrypted_ec075ad0bd66_key -iv $encrypted_ec075ad0bd66_iv -in keys.txt.enc -out keys.txt -d
install:
  - pip install requests
# command to run tests
script:
  - python APIAggregator_github.py 
